---
apt_packages:
  - git
  - xsel
  - xclip
  - tree
  - libpoppler-cpp-dev
  - htop
  - vim
  - vim-common
  - vim-gtk3
  - vim-gui-common
  - vim-nox
  - vim-runtime
  - vim-tiny
    # - rxvt-unicode-256color
  - tmux
  - tmux-plugin-manager
  - pandoc
  - exfatprogs
  - shellcheck
  - terminator
  - gparted
  - nvme-cli
  - smartmontools
  - pkg-config
  - g++
  - python3-dev
  - lvm2
  - exiftool

brew_bin_real_path_default: /home/linuxbrew/.linuxbrew/bin/brew
brew_bin_venv_path: '{{ project_root_path }}/.venv/bin/brew'
brew_exec_venv_path: '{{ brew_bin_venv_path|dirname }}'

brews:
  - formulae: bat
  - formulae: fzf
  - formulae: ripgrep
