---
apt_packages:
  - git
  - xsel
  - xclip
  - tree
  - libpoppler-cpp-dev
  - htop
  - vim
  - vim-common
  - vim-gtk3
  - vim-gui-common
  - vim-nox
  - vim-runtime
  - vim-tiny
    # - rxvt-unicode-256color
  - tmux
  - tmux-plugin-manager
  - pandoc
  - exfatprogs
  - shellcheck
  - terminator
  - gparted
  - nvme-cli
  - smartmontools
  - pkg-config
  - g++
  - python3-dev
  - lvm2
  - exiftool
