---
name: nas
properties:
  type: smb
  host: nas
  user: "{{ (lookup('file', secrets_path + '/nas/credentials.yml')|from_yaml).admin.username }}"
  pass: "{{ (lookup('file', secrets_path + '/nas/credentials.yml')|from_yaml).admin.password_obscure }}"
