---
name: nas
properties:
  type: cifs
  host: nas
  smb_user: "{{ (lookup('file', secrets_path + '/nas/credentials.yml')|from_yaml).admin.username }}"
  smb_pass: "{{ (lookup('file', secrets_path + '/nas/credentials.yml')|from_yaml).admin.password }}"
